USE [master]

/****** Object:  Database [AutonomerSDB]    Script Date: 27.05.2022 8:09:27 ******/
CREATE DATABASE [AutonomerSDB]
 CONTAINMENT = NONE
 WITH CATALOG_COLLATION = DATABASE_DEFAULT

ALTER DATABASE [AutonomerSDB] SET COMPATIBILITY_LEVEL = 150

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AutonomerSDB].[dbo].[sp_fulltext_database] @action = 'enable'
end

ALTER DATABASE [AutonomerSDB] SET ANSI_NULL_DEFAULT OFF 

ALTER DATABASE [AutonomerSDB] SET ANSI_NULLS OFF 

ALTER DATABASE [AutonomerSDB] SET ANSI_PADDING OFF 

ALTER DATABASE [AutonomerSDB] SET ANSI_WARNINGS OFF 

ALTER DATABASE [AutonomerSDB] SET ARITHABORT OFF 

ALTER DATABASE [AutonomerSDB] SET AUTO_CLOSE OFF 

ALTER DATABASE [AutonomerSDB] SET AUTO_SHRINK OFF 

ALTER DATABASE [AutonomerSDB] SET AUTO_UPDATE_STATISTICS ON 

ALTER DATABASE [AutonomerSDB] SET CURSOR_CLOSE_ON_COMMIT OFF 

ALTER DATABASE [AutonomerSDB] SET CURSOR_DEFAULT  GLOBAL 

ALTER DATABASE [AutonomerSDB] SET CONCAT_NULL_YIELDS_NULL OFF 

ALTER DATABASE [AutonomerSDB] SET NUMERIC_ROUNDABORT OFF 

ALTER DATABASE [AutonomerSDB] SET QUOTED_IDENTIFIER OFF 

ALTER DATABASE [AutonomerSDB] SET RECURSIVE_TRIGGERS OFF 

ALTER DATABASE [AutonomerSDB] SET  DISABLE_BROKER 

ALTER DATABASE [AutonomerSDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 

ALTER DATABASE [AutonomerSDB] SET DATE_CORRELATION_OPTIMIZATION OFF 

ALTER DATABASE [AutonomerSDB] SET TRUSTWORTHY OFF 

ALTER DATABASE [AutonomerSDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 

ALTER DATABASE [AutonomerSDB] SET PARAMETERIZATION SIMPLE 

ALTER DATABASE [AutonomerSDB] SET READ_COMMITTED_SNAPSHOT OFF 

ALTER DATABASE [AutonomerSDB] SET HONOR_BROKER_PRIORITY OFF 

ALTER DATABASE [AutonomerSDB] SET RECOVERY SIMPLE 

ALTER DATABASE [AutonomerSDB] SET  MULTI_USER 

ALTER DATABASE [AutonomerSDB] SET PAGE_VERIFY CHECKSUM  

ALTER DATABASE [AutonomerSDB] SET DB_CHAINING OFF 

ALTER DATABASE [AutonomerSDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 

ALTER DATABASE [AutonomerSDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 

ALTER DATABASE [AutonomerSDB] SET DELAYED_DURABILITY = DISABLED 

ALTER DATABASE [AutonomerSDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  

EXEC sys.sp_db_vardecimal_storage_format N'AutonomerSDB', N'ON'

ALTER DATABASE [AutonomerSDB] SET QUERY_STORE = OFF
GO
USE [AutonomerSDB]

/****** Object:  Table [dbo].[Records]    Script Date: 27.05.2022 8:09:27 ******/
SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[Records](
	[Uid] [uniqueidentifier] NOT NULL,
	[CameraName] [nvarchar](128) NOT NULL,
	[Date] [datetime] NOT NULL,
	[CarNumber] [nvarchar](128) NOT NULL,
	[Image] [varbinary](max) NOT NULL,
 CONSTRAINT [PK_Records] PRIMARY KEY CLUSTERED 
(
	[Uid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

ALTER TABLE [dbo].[Records] ADD  CONSTRAINT [DF_Table_1_Id]  DEFAULT (newid()) FOR [Uid]

USE [master]

ALTER DATABASE [AutonomerSDB] SET  READ_WRITE 

